name: Create release

on:
#  schedule:
#    - cron:  '0 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      rooted-graphene-version:
        description: Git ref of rooted graphene repo to use
        required: false
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rooted-graphene script repository
        uses: actions/checkout@v5
        with:
          repository: schnatterer/rooted-graphene
          ref: ${{ github.event.inputs.rooted-graphene-version || inputs.rooted-graphene-version || 'main' }} 
          fetch-depth: 1 # Efficent checkout, we only need the one ref
      - name: Set inputs
        # Empty means, use version defined in rooted-ota.sh
        # Just pick an arbitrary device
        run: |
          echo "DEVICE_ID=caiman" >> $GITHUB_ENV
      - run: sudo apt-get install -y jq curl git
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          DEBUG=1 bash -c '. rooted-ota.sh && findLatestVersion && checkBuildNecessary && createReleaseIfNecessary'